-- AlterTable
ALTER TABLE "GoogleAccount" ADD COLUMN     "connectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "expiresAt" TIMESTAMP(3),
ADD COLUMN     "scopes" TEXT,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'CONNECTED';
